# Generated by Django 3.1.5 on 2022-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '결제', 'verbose_name_plural': '결제'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='결제일'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='결제',
        ),
    ]
