# Generated by Django 3.1.5 on 2022-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221031_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(null=True, verbose_name='핸드폰번호'),
        ),
    ]
