# Generated by Django 3.1.5 on 2022-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221031_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(null=True, unique=True, verbose_name='핸드폰번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=17, unique=True, verbose_name='아이디'),
        ),
    ]
