# Generated by Django 3.1.5 on 2022-11-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221031_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='circles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('미선택', '미선택'), ('Korea', 'Korea'), ('US', 'US'), ('Japan', 'Japan'), ('China', 'China'), ('Others', 'Others')], max_length=18, null=True, verbose_name='국적'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='사용자',
        ),
    ]
