# Generated by Django 3.1.5 on 2022-11-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_category_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
