# Generated by Django 3.1.5 on 2022-11-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_order_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='경도')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.product', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '지도',
                'verbose_name_plural': '지도',
                'db_table': '지도',
            },
        ),
    ]
