# Generated by Django 3.1.5 on 2022-11-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.FloatField(verbose_name='경도'),
        ),
    ]
