# Generated by Django 3.1.5 on 2022-11-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20221101_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
