# Generated by Django 3.1.5 on 2022-11-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20221101_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품'),
        ),
    ]
