# Generated by Django 3.1.5 on 2022-11-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='order',
            name='auth',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='인증번호'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='order',
            name='hp',
            field=models.IntegerField(null=True, verbose_name='핸드폰번호'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.CharField(choices=[('3', 'Lv3_미인증사용자'), ('2', 'Lv2_인증사용자'), ('1', 'Lv1_관리자'), ('0', 'Lv0_개발자')], default=3, max_length=18, verbose_name='등급'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=8, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='', max_length=256, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=17, verbose_name='아이디'),
        ),
    ]
