# Generated by Django 3.1.5 on 2022-11-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_order_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
