# Generated by Django 3.1.5 on 2022-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_order_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
