# Generated by Django 3.1.5 on 2022-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grade',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=18, null=True, verbose_name='인원'),
        ),
    ]
